<?php

return [
    [
        'question' => "What is the color of the recycling bin for paper?",
        'answer_a' => "Blue",
        'answer_b' => "Red",
        'answer_c' => "Yellow",
        'answer_d' => "Green",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a renewable energy source?",
        'answer_a' => "Coal",
        'answer_b' => "Solar",
        'answer_c' => "Oil",
        'answer_d' => "Natural Gas",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the main purpose of composting?",
        'answer_a' => "Creating trash",
        'answer_b' => "Recycling paper",
        'answer_c' => "Turning waste into nutrient-rich soil",
        'answer_d' => "Producing electricity",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a non-renewable resource?",
        'answer_a' => "Wind",
        'answer_b' => "Oil",
        'answer_c' => "Sun",
        'answer_d' => "Plants",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of the ozone layer in the atmosphere?",
        'answer_a' => "Trap heat",
        'answer_b' => "Protect against harmful ultraviolet (UV) rays",
        'answer_c' => "Produce oxygen",
        'answer_d' => "Generate rain",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to conserve water?",
        'answer_a' => "Leaving the tap running while brushing teeth",
        'answer_b' => "Taking long showers",
        'answer_c' => "Fixing leaking faucets",
        'answer_d' => "Watering the garden every day",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the primary source of energy for plants?",
        'answer_a' => "Soil",
        'answer_b' => "Water",
        'answer_c' => "Sunlight",
        'answer_d' => "Air",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to reduce air pollution?",
        'answer_a' => "Planting more trees",
        'answer_b' => "Burning more fossil fuels",
        'answer_c' => "Using more plastic",
        'answer_d' => "Disposing of waste in rivers",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "What can you do to reduce your carbon footprint?",
        'answer_a' => "Use energy-efficient appliances",
        'answer_b' => "Leave lights on when not needed",
        'answer_c' => "Drive a gas-guzzling car",
        'answer_d' => "Keep the computer on all night",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a biodegradable material?",
        'answer_a' => "Plastic",
        'answer_b' => "Glass",
        'answer_c' => "Paper",
        'answer_d' => "Metal",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a wildlife sanctuary?",
        'answer_a' => "To capture wild animals",
        'answer_b' => "To provide a safe habitat for animals",
        'answer_c' => "To build amusement parks",
        'answer_d' => "To mine natural resources",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the main component of the Earth's atmosphere?",
        'answer_a' => "Oxygen",
        'answer_b' => "Carbon Dioxide",
        'answer_c' => "Nitrogen",
        'answer_d' => "Hydrogen",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a non-renewable resource?",
        'answer_a' => "Wind",
        'answer_b' => "Natural Gas",
        'answer_c' => "Geothermal energy",
        'answer_d' => "Tidal energy",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What should you do with plastic bottles after use?",
        'answer_a' => "Throw them in the trash",
        'answer_b' => "Recycle them",
        'answer_c' => "Bury them in the garden",
        'answer_d' => "Burn them",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of the Greenhouse Effect?",
        'answer_a' => "Cool the Earth",
        'answer_b' => "Trap heat in the Earth's atmosphere",
        'answer_c' => "Prevent the Sun's rays from reaching Earth",
        'answer_d' => "Create artificial ecosystems",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a source of water pollution?",
        'answer_a' => "Proper waste disposal",
        'answer_b' => "Recycling",
        'answer_c' => "Oil spills",
        'answer_d' => "Planting trees",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the best way to dispose of old electronics?",
        'answer_a' => "Throw them in the regular trash",
        'answer_b' => "Recycle them at an e-waste facility",
        'answer_c' => "Bury them in the backyard",
        'answer_d' => "Burn them",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a renewable resource?",
        'answer_a' => "Coal",
        'answer_b' => "Natural Gas",
        'answer_c' => "Biomass",
        'answer_d' => "Nuclear energy",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a rain garden?",
        'answer_a' => "To create floods",
        'answer_b' => "To collect rainwater for drinking",
        'answer_c' => "To prevent soil erosion",
        'answer_d' => "To grow vegetables",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the main cause of deforestation?",
        'answer_a' => "Planting more trees",
        'answer_b' => "Urbanization",
        'answer_c' => "Protecting wildlife",
        'answer_d' => "Recycling paper",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of wetlands in the ecosystem?",
        'answer_a' => "Provide a habitat for mosquitoes",
        'answer_b' => "Filter and purify water",
        'answer_c' => "Create deserts",
        'answer_d' => "Prevent rainfall",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the role of bees in the environment?",
        'answer_a' => "Spread diseases",
        'answer_b' => "Pollinate plants",
        'answer_c' => "Create honey",
        'answer_d' => "Attack humans",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the main cause of air pollution in cities?",
        'answer_a' => "Planting more trees",
        'answer_b' => "Using public transportation",
        'answer_c' => "Industrial emissions",
        'answer_d' => "Opening windows",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a wildlife corridor?",
        'answer_a' => "Trap animals",
        'answer_b' => "Provide a safe passage for animals",
        'answer_c' => "Build roads",
        'answer_d' => "Create a zoo",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of the Red List of Threatened Species?",
        'answer_a' => "List dangerous animals",
        'answer_b' => "Identify endangered species",
        'answer_c' => "Plan hunting trips",
        'answer_d' => "Decorate classrooms",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the main source of water pollution in rivers and lakes?",
        'answer_a' => "Proper waste disposal",
        'answer_b' => "Agricultural runoff",
        'answer_c' => "Recycling facilities",
        'answer_d' => "Fishing",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a solar-powered water heater?",
        'answer_a' => "Increase electricity bills",
        'answer_b' => "Reduce the need for electricity",
        'answer_c' => "Generate more pollution",
        'answer_d' => "Create a cooling effect",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a wildlife conservation area?",
        'answer_a' => "Build shopping malls",
        'answer_b' => "Protect and preserve natural habitats",
        'answer_c' => "Create pollution",
        'answer_d' => "Hunt animals",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a bicycle lane?",
        'answer_a' => "Create more traffic",
        'answer_b' => "Provide a safe space for cyclists",
        'answer_c' => "Build more roads",
        'answer_d' => "Encourage more driving",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is a cause of soil erosion?",
        'answer_a' => "Planting more trees",
        'answer_b' => "Building terraces",
        'answer_c' => "Deforestation",
        'answer_d' => "Using organic farming methods",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a solar cooker?",
        'answer_a' => "Increase electricity bills",
        'answer_b' => "Reduce the need for electricity",
        'answer_c' => "Produce more heat",
        'answer_d' => "Use more fossil fuels",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the main cause of coral reef degradation?",
        'answer_a' => "Protecting coral reefs",
        'answer_b' => "Overfishing",
        'answer_c' => "Creating marine reserves",
        'answer_d' => "Using sustainable fishing methods",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a rain barrel?",
        'answer_a' => "Create floods",
        'answer_b' => "Collect and store rainwater for later use",
        'answer_c' => "Waste water",
        'answer_d' => "Dump water into rivers",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the main source of light on Earth?",
        'answer_a' => "Moon",
        'answer_b' => "Sun",
        'answer_c' => "Stars",
        'answer_d' => "Fire",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What do plants need to make their own food?",
        'answer_a' => "Water and sunlight",
        'answer_b' => "Soil and rocks",
        'answer_c' => "Air and fire",
        'answer_d' => "Ice and snow",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a non-renewable resource?",
        'answer_a' => "Solar power",
        'answer_b' => "Wind energy",
        'answer_c' => "Fossil fuels",
        'answer_d' => "Geothermal energy",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What gas do humans breathe in?",
        'answer_a' => "Oxygen",
        'answer_b' => "Carbon dioxide",
        'answer_c' => "Nitrogen",
        'answer_d' => "Hydrogen",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of composting?",
        'answer_a' => "Creating energy",
        'answer_b' => "Recycling paper",
        'answer_c' => "Turning waste into soil",
        'answer_d' => "Generating heat",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "Which of these activities helps conserve water?",
        'answer_a' => "Taking long showers",
        'answer_b' => "Leaving the faucet running while washing dishes",
        'answer_c' => "Turning faucet off while brushing teeth",
        'answer_d' => "Watering the garden in the middle of the day",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What should you do with old and unwanted clothes?",
        'answer_a' => "Throw them in the trash",
        'answer_b' => "Donate or recycle them",
        'answer_c' => "Burn them",
        'answer_d' => "Bury them in the backyard",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a natural habitat for fish?",
        'answer_a' => "Plastic bag",
        'answer_b' => "Aquarium",
        'answer_c' => "Ocean",
        'answer_d' => "Bathtub",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the color of the bin for glass recycling?",
        'answer_a' => "Green",
        'answer_b' => "Blue",
        'answer_c' => "Yellow",
        'answer_d' => "Brown",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to reduce air pollution?",
        'answer_a' => "Using public transportation",
        'answer_b' => "Burning more fossil fuels",
        'answer_c' => "Cutting down more trees",
        'answer_d' => "Using plastic bags",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "What is the primary source of energy for most electronics?",
        'answer_a' => "Water",
        'answer_b' => "Sun",
        'answer_c' => "Electricity",
        'answer_d' => "Wind",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "Which of these is a renewable resource derived from plants?",
        'answer_a' => "Oil",
        'answer_b' => "Natural Gas",
        'answer_c' => "Biofuel",
        'answer_d' => "Coal",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What can you do to save energy at home?",
        'answer_a' => "Keep lights and appliances on all the time",
        'answer_b' => "Turn off lights and appliances when not in use",
        'answer_c' => "Open windows in winter to heat the house",
        'answer_d' => "Use incandescent light bulbs",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a renewable resource used for making furniture?",
        'answer_a' => "Plastic",
        'answer_b' => "Metal",
        'answer_c' => "Wood",
        'answer_d' => "Glass",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What should you do with used batteries?",
        'answer_a' => "Throw them in the regular trash",
        'answer_b' => "Recycle them at a designated facility",
        'answer_c' => "Bury them in the backyard",
        'answer_d' => "Burn them",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to reduce plastic pollution in the oceans?",
        'answer_a' => "Dump plastic waste into rivers",
        'answer_b' => "Use more single-use plastic",
        'answer_c' => "Recycle plastic bottles",
        'answer_d' => "Ignore the issue",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the largest source of marine pollution?",
        'answer_a' => "Oil spills",
        'answer_b' => "Plastic waste",
        'answer_c' => "Sewage",
        'answer_d' => "Radioactive waste",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of wetlands in the environment?",
        'answer_a' => "Providing habitat for wildlife",
        'answer_b' => "Wasting water",
        'answer_c' => "Storing nuclear waste",
        'answer_d' => "Creating deserts",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to reduce carbon footprint?",
        'answer_a' => "Planting more trees",
        'answer_b' => "Using more fossil fuels",
        'answer_c' => "Leaving lights on all day",
        'answer_d' => "Driving alone in a car",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "What is the primary source of air pollution in cities?",
        'answer_a' => "Cars and trucks",
        'answer_b' => "Trees and plants",
        'answer_c' => "Rain",
        'answer_d' => "Birds",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "What is the color of the bin for plastic?",
        'answer_a' => "Yellow",
        'answer_b' => "Blue",
        'answer_c' => "Green",
        'answer_d' => "Silver",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a natural habitat for polar bears?",
        'answer_a' => "Desert",
        'answer_b' => "Rainforest",
        'answer_c' => "Tundra",
        'answer_d' => "Mountains",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a wildlife reserve or sanctuary?",
        'answer_a' => "Hunting",
        'answer_b' => "Protection of endangered species and their habitats",
        'answer_c' => "Creating a zoo",
        'answer_d' => "Deforestation",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a source of noise pollution?",
        'answer_a' => "Singing birds",
        'answer_b' => "Wind blowing",
        'answer_c' => "Traffic and construction noise",
        'answer_d' => "Ocean waves",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the color of the bin for electronic waste (e-waste) recycling?",
        'answer_a' => "Red",
        'answer_b' => "Green",
        'answer_c' => "Blue",
        'answer_d' => "Orange",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to conserve energy in the summer?",
        'answer_a' => "Turning on all lights",
        'answer_b' => "Using air conditioning excessively",
        'answer_c' => "Opening windows at night",
        'answer_d' => "Leaving doors open",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "What is the color of the bin for biodegradable waste?",
        'answer_a' => "Green",
        'answer_b' => "Blue",
        'answer_c' => "Brown",
        'answer_d' => "Red",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to protect soil from erosion?",
        'answer_a' => "Planting trees and grass",
        'answer_b' => "Leaving soil bare",
        'answer_c' => "Dumping chemicals",
        'answer_d' => "Ignoring the issue",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a solar panel?",
        'answer_a' => "Creating shade",
        'answer_b' => "Generating electricity from sunlight",
        'answer_c' => "Attracting birds",
        'answer_d' => "Blocking sunlight",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a source of indoor air pollution?",
        'answer_a' => "Opening windows",
        'answer_b' => "Burning candles",
        'answer_c' => "Having houseplants",
        'answer_d' => "Using air purifiers",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a bicycle lane on the road?",
        'answer_a' => "Racing",
        'answer_b' => "Parking",
        'answer_c' => "Riding bicycles safely",
        'answer_d' => "Planting trees",
        'correct' => 3,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to reduce plastic use in daily life?",
        'answer_a' => "Buying single-use plastic products",
        'answer_b' => "Using reusable bags and containers",
        'answer_c' => "Ignoring plastic waste",
        'answer_d' => "Throwing plastic in the ocean",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a wind turbine?",
        'answer_a' => "Creating windstorms",
        'answer_b' => "Generating electricity from the wind",
        'answer_c' => "Blocking the wind",
        'answer_d' => "Attracting birds",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "What is the purpose of a rain barrel?",
        'answer_a' => "Creating floods",
        'answer_b' => "Collecting rainwater for later use",
        'answer_c' => "Throwing trash",
        'answer_d' => "Storing oil",
        'correct' => 2,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to reduce deforestation?",
        'answer_a' => "Planting more trees",
        'answer_b' => "Cutting down more trees",
        'answer_c' => "Ignoring the issue",
        'answer_d' => "Using paper excessively",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "What is the color of the bin for metal recycling?",
        'answer_a' => "Yellow",
        'answer_b' => "Blue",
        'answer_c' => "Green",
        'answer_d' => "Silver",
        'correct' => 1,
        'prize' => 50,
    ],
    [
        'question' => "Which of the following is a way to reduce plastic straw use?",
        'answer_a' => "Using plastic straws for every drink",
        'answer_b' => "Using reusable or paper straws",
        'answer_c' => "Ignoring plastic pollution",
        'answer_d' => "Throwing straws in the ocean",
        'correct' => 2,
        'prize' => 50,
    ],
];
